- input:
    - static/ts/login.ts
  output:
    - dir: public/js
      format: esm
      entryFileNames: 'esm/[name]-[hash].min.mjs'
      chunkFileNames: 'esm/[name]-[hash].min.mjs'
    - dir: public/js
      format: system
      entryFileNames: 'system/[name]-[hash].min.js'
      chunkFileNames: 'system/[name]-[hash].min.js'
  plugins:
    - name: del
      api:
        targets: public/js/{esm,system}/*.{js,mjs}
    - name: typescript
      api:
        tsconfig: tsconfig.browser.json
    - name: commonjs
    - name: nodeResolve
      api:
        mainFields:
          - jsnext:main
          - module
          - main
    - name: json
    - name: terser
    - name: metadata
- input: static/js/import.js
  output:
    dir: public/js
    format: iife
    entryFileNames: 'system/[name]-[hash].min.js'
  plugins:
    - name: commonjs
    - name: nodeResolve
      api:
        mainFields:
          - jsnext:main
          - module
          - main
    - name: json
    - name: terser
    - name: metadata
- input: static/scss/style.scss
  output:
    dir: public/css
    assetFileNames: '[name]-[hash][extname]'
  plugins:
    - name: del
      api:
        targets: public/css/*
    - name: styles
      api:
        mode: extract
        sass:
          impl: sass
          fibers: false
          sync: true
        minimize: true
    - name: del
      api:
        targets: public/css/*.js
        hook: writeBundle
    - name: metadata
