- input:
    - src_client/ts/global.ts
    - src_client/ts/login.ts
    - src_client/ts/webauthn.ts
    - src_client/ts/login_authenticator.ts
    - src_client/ts/webauthn_authenticator.ts
    - src_client/ts/end.ts
    - src_client/ts/error.ts
  output:
    - dir: public/js
      format: esm
      entryFileNames: 'esm/[name]-[hash].min.mjs'
      chunkFileNames: 'esm/[name]-[hash].min.mjs'
      preferConst: true
    - dir: public/js
      format: system
      entryFileNames: 'system/[name]-[hash].min.js'
      chunkFileNames: 'system/[name]-[hash].min.js'
  plugins:
    - name: del
      api:
        targets: public/js/{esm,system}/*.{js,mjs}
    - name: typescript
      api:
        tsconfig: tsconfig.browser.json
    - name: nodeResolve
      api:
        mainFields:
          - es2015
          - module
          - main
    - name: terser
    - name: cleanComments
    - name: metadata
- input: src_client/js/import.js
  output:
    dir: public/js
    format: iife
    entryFileNames: 'system/[name]-[hash].min.js'
  plugins:
    - name: nodeResolve
    - name: terser
    - name: cleanComments
    - name: metadata
- input: src_client/scss/style.scss
  output:
    dir: public/css
    assetFileNames: '[name]-[hash][extname]'
  plugins:
    - name: del
      api:
        targets: public/css/*.css
    - name: styles
      api:
        mode: extract
        sass:
          impl: sass
          fibers: false
          sync: true
          includePaths:
            - node_modules
        minimize: true
    - name: del
      api:
        targets: public/css/*.js
        hook: writeBundle
    - name: metadata
