server:
  protocol: http
  host: 0.0.0.0
  port: 3000
  isSSL: false
  options:
    logger: true
views:
  templatesPath: ../static/views
  layout: _layout
  includeViewExtension: true
  engineOptions:
    async: true
    htmlMinifierOptions:
      removeComments: true
      removeCommentsFromCDATA: true
      collapseWhitespace: true
      collapseBooleanAttributes: true
      removeEmptyAttributes: true
      minifyCSS: true
      minifyJS: true
  defaultContext:
    title: Fido2 WebAuthn + OpenID Connect
assets:
  rootPath: ../public
  options:
    prefix: /public/
    cacheControl: true
    etag: true
    acceptRanges: true
    lastModified: true
    immutable: true
    maxAge: 86400000
  styleCompiler:
    requestPathToExecute: /public/css
    scssPath: ../static/scss
    outFile: style.css
    outFolder: css
    options:
      outputStyle: compressed
      response: false
      sourceMap: true
      sourceMapEmbed: true
      debug: false
pipes:
  validation:
    whitelist: true
    forbidNonWhitelisted: true
