server:
  protocol: http
  host: 0.0.0.0
  port: 3000
  views:
    templatesPath: ../views
    layout: _layout
    title: Fido2 WebAuthn + OpenID Connect
  assets:
    rootPath: ../public
    prefix: /
