server:
  protocol:
    normal: http
    secure: https
  host: 0.0.0.0
  port: 3000
  isSSL: true
  runInHTTPS: true
  options:
    - name: logger
      value: true
    - name: https
      value:
        pfx:
          path: ../ssl/ssl.p12

views:
  templatesPath: ../views
  layout: _layout
  includeViewExtension: true
  engineOptions:
    async: true
    htmlMinifierOptions:
      removeComments: true
      removeCommentsFromCDATA: true
      collapseWhitespace: true
      collapseBooleanAttributes: true
      removeEmptyAttributes: true
      minifyCSS: true
      minifyJS: true
    partials:
      webauthn-dialog: _webauthn_dialog.hbs
      webauthn-dialog-register: _webauthn_dialog_content_register.hbs
      webauthn-dialog-verify: _webauthn_dialog_content_verify.hbs
      webauthn-dialog-edit: _webauthn_dialog_content_edit.hbs
  defaultContext:
    title: Fido2 WebAuthn + OpenID Connect
  i18n:
    login:
      headerTitle: Login Has Never Been Easier-Or Safer!
      pageTitle: Login with password
      loginButton: Login
      text1: Looking for a better way to login ? Click
      text2: if you already have registered a Fido authenticator and you want to connect via on-device biometrics instead of passwords.
      here: here
      username: Username
      password: Password
      errorWebAuthn: Your browser doesn't support WebAuthn protocol
    login_authenticator:
      headerTitle: Fido 2 WebAuthn - Security Settings
      pageTitle: Welcome
      congratulations: Congratulations ! You have successfully signed in.
      advices: To safeguard your account further, we recommend you to enroll First-Factor authenticator and stop using your username and password.
      enrollment: To do this, simply click on the button and you will be redirected to your authenticator management page in order to enroll a security key or Biometrics.
      startEnrollment: Start Enrollment
      skipEnrollment: Select this checkbox if you want to skip the enrollment and no longer display this page next time. We do not recommend it to you.
      errorWebAuthn: Your browser doesn't support WebAuthn protocol
    webauthn_authenticator:
      headerTitle: Fido 2 WebAuthn - Security Settings
      pageTitle: First-Factor Authentication
      text1: Configure your first-factor authentication here. You can select any combination of authenticators, including multiple security keys and any combination of security keys and internal authenticators.
      text2: Once an authenticator has been selected you can
      text3: and then sign in to experience the WebAuthn authentication.
      signOut: sign out
      biometrics: Biometrics
      biometric: Biometric
      securityKeys: Security Keys
      securityKey: Security Key
      addbBiometric: Add Biometric
      addSecurityKey: Add Security Key
      errorWebAuthn: Your browser doesn't support WebAuthn protocol
      loading: Loading...
      cancel: Cancel
      register: Register
      registerSecurityKeyTitle: Do you have a security key ?
      registerSecurityKeyInfo: To register a security key insert it into the USB port and press NEXT. When it starts flashing, press the gold disc on it.
      edit: Edit
      done: Done
      remove: Remove
      createdAt: Registration date
      labelEditInput: Name your authenticator
      processTitle: Interact with your authenticator
      errorRegisterMessage: There was an error in the registration procedure, please try again
      successTitle: You have successfully registered your authenticator
    end:
      headerTitle: Login Has Never Been Easier-Or Safer!
      pageTitle: Welcome
      congratulations: Congratulations ! You have successfully signed in.
      text: You are on the last page of this demonstration. You can nevertheless access the management page of your authenticator or simply log out to start the process again.
      webauthn1: We hope you enjoyed this new authentication experience and that you will never want to use a password again in the future.
      webauthn2: Talk to those around you and ask that the WebAuthn protocol be integrated into as many applications as possible so that everyone enjoys maximum security.
      advices: To safeguard your account further, we recommend you to enroll First-Factor authenticator and stop using your username and password.
      enrollment: To do this, simply click on the button and you will be redirected to your authenticator management page in order to enroll a security key or Biometrics.
      authenticators: Authenticator
      logout: Logout
      errorWebAuthn: Your browser doesn't support WebAuthn protocol
    error:
      headerTitle: Login Has Never Been Easier-Or Safer!
      pageTitle: An error occurred
      text: The requested page does not exist or you are not authorized to access it, please click on the button to restart the authentication process.
      restartAuthentication: Restart Authentication

assets:
  rootPath: ../public
  options:
    prefix: /public/
    cacheControl: true
    etag: true
    acceptRanges: true
    lastModified: true
    maxAge: 86400000

pipes:
  validation:
    whitelist: true
    forbidNonWhitelisted: true

swagger:
  title: Fido2 WebAuthn + OpenID Connect
  description: API description
  version: 0.1.0
  tag: api
  path: documentation

mongodb:
  uri: mongodb://0.0.0.0:27017/authenticationservice
  options:
    useNewUrlParser: true
    useUnifiedTopology: true
    useFindAndModify: false

security:
  password:
    salt: Ahshah2aeh0fevie
    iterations: 4096
    keylen: 24
    digest: sha512
  session:
    cookieName: webauthn_openidconnect_server_session
    secret: KubSwPuVTZf1qGIrNymxTbOwye8QxFwMGv14rZmvNYK1kdkzkkGvFWdKDoeGsS9iP
    salt: uJapbvAN6lkYxFwM
    cookie:
      path: /
      httpOnly: true
      secure: true
      sameSite: true
      maxAge: 1800
  webauthn:
    rpName: Fido2 WebAuthn Example by Akanass
    rpID: akanass.local
    rpPort: 3000
    useRpPort: true
    timeout: 60000
    attestationType: direct
    authenticatorSelection:
      residentKey: required
      userVerification: required
    defaultSecurityKeyName: My Security Key Authenticator
    defaultBiometricName: My Biometric Authenticator
    defaultTransports:
      - ble
      - internal
      - nfc
      - usb
