server:
  protocol:
    normal: http
    secure: https
  host: 0.0.0.0
  port: 3000
  isSSL: true
  options:
    - name: logger
      value: true
    - name: https
      value:
        pfx:
          path: ../ssl/ssl.p12
views:
  templatesPath: ../views
  layout: _layout
  includeViewExtension: true
  engineOptions:
    async: true
    htmlMinifierOptions:
      removeComments: true
      removeCommentsFromCDATA: true
      collapseWhitespace: true
      collapseBooleanAttributes: true
      removeEmptyAttributes: true
      minifyCSS: true
      minifyJS: true
  defaultContext:
    title: Fido2 WebAuthn + OpenID Connect
  i18n:
    login:
      unsupported: Your browser doesn't support WebAuthn protocol :( - You have to update it or having an SSL connection if you want to enjoy those new features !!!
      headerTitle: Login Has Never Been Easier-Or Safer!
      pageTitle: Login
      loginButton: Login
      text1: Looking for a better way to login ? Click
      text2: if you already have registered a Fido authenticator and you want to connect via on-device biometrics instead of passwords.
      here: here
      username: Username
      password: Password
assets:
  rootPath: ../public
  options:
    prefix: /public/
    cacheControl: true
    etag: true
    acceptRanges: true
    lastModified: true
    maxAge: 86400000
pipes:
  validation:
    whitelist: true
    forbidNonWhitelisted: true
